version: "3.9"
services:
  mongodb:
    image: mongo:7.0
    container_name: furniro-mongo
    command: [ "mongod", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - furniro-network
    environment:
      MONGO_INITDB_DATABASE: "furniro"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10


  backend:

    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: furniro-backend
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/furniro
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - furniro-network
    restart: unless-stopped

  frontend:

    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: furniro-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - furniro-network
    restart: unless-stopped

networks:
  furniro-network:
    driver: bridge

volumes:
  mongodb_data:
