version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: furniro-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: furniro
    volumes:
      - mongodb_data:/data/db
    networks:
      - furniro-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/furniro --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/round-centaur-477210-k3/ankur/backend:1.0
    container_name: furniro-backend
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - furniro-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/round-centaur-477210-k3/ankur/frontend:1.0
    container_name: furniro-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - furniro-network
    restart: unless-stopped

networks:
  furniro-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
